# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'build glove80'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["glove80_lh","glove80_rh"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
